name: Write.as Publish Scheduler

on:
  push:
  schedule:
      - cron: "0 22 * * 1-5"

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/writeas-publish
        with:
          blog: "the-test-blog"
          token: ${{ secrets.TOKEN }}